### ISSUE TITLE
Error on execution

### ISSUE THREAD

**Issue by guigomesa** [nicoddemus/ss#48]
On execute in folder scan

below stacktrace

Traceback (most recent call last):
  File "/usr/local/bin/ss", line 11, in <module>
    sys.exit(main())
  File "/usr/local/bin/ss.py", line 381, in main
    subtitle_filename = future.result()
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 400, in result
    return self.__get_result()
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 359, in __get_result
    reraise(self._exception, self._traceback)
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_compat.py", line 107, in reraise
    exec('raise exc_type, exc_value, traceback', {}, locals_)
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/thread.py", line 61, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/bin/ss.py", line 189, in search_and_download
    download_subtitle(subtitle_url, subtitle_filename)
  File "/usr/local/bin/ss.py", line 138, in download_subtitle
    subtitle_contents = f.read()
  File "/usr/lib/python2.7/gzip.py", line 254, in read
    self._read(readsize)
  File "/usr/lib/python2.7/gzip.py", line 296, in _read
    self._read_gzip_header()
  File "/usr/lib/python2.7/gzip.py", line 190, in _read_gzip_header
    raise IOError, 'Not a gzipped file'

**Comment by nicoddemus** [comment]
Hi!

Weird, from the documentation all opensubtitles files should be in gzipped.

Can you open `/usr/local/bin/ss.py` in line `125` and print which url it is trying to download? 

Something like:

```python
def download_subtitle(subtitle_url, subtitle_filename):
    print '*****', subtitle_url    
    # first download it and save to a temp dir
    with closing(urlopen(subtitle_url)) as urlfile:
        gzip_subtitle_contents = urlfile.read()
    ...
```

If you send that url to me I can try to investigate what is happening and hopefully fix this, or at least give a better error message. :smile:

Cheers!

**Comment by guigomesa** [comment]
the last url and stack trace

***** http://dl.opensubtitles.org/en/download/filead/src-api/vrf-f1df5e6647/sid-59u5ljvife6rlktcl486ebmm80/1954156799.gz
Traceback (most recent call last):
  File "/usr/local/bin/ss", line 11, in <module>
    sys.exit(main())
  File "/usr/local/bin/ss.py", line 382, in main
    subtitle_filename = future.result()
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 400, in result
    return self.__get_result()
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 359, in __get_result
    reraise(self._exception, self._traceback)
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_compat.py", line 107, in reraise
    exec('raise exc_type, exc_value, traceback', {}, locals_)
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/thread.py", line 61, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/bin/ss.py", line 190, in search_and_download
    download_subtitle(subtitle_url, subtitle_filename)
  File "/usr/local/bin/ss.py", line 139, in download_subtitle
    subtitle_contents = f.read()
  File "/usr/lib/python2.7/gzip.py", line 254, in read
    self._read(readsize)
  File "/usr/lib/python2.7/gzip.py", line 296, in _read
    self._read_gzip_header()
  File "/usr/lib/python2.7/gzip.py", line 190, in _read_gzip_header
    raise IOError, 'Not a gzipped file'
IOError: Not a gzipped file

**Comment by guigomesa** [comment]
And my config file

Configuration read from /home/guigomesa/.ss.ini
languages = pob
recursive = True
skip = True
mkv = False
parallel_jobs = 8

Languages: pob

**Comment by nicoddemus** [comment]
Hi,

Thanks for posting this.

I tried to reproduce the problem but I couldn't, unfortunately. Can you please create this script file:

```python
from contextlib import closing
import gzip
from urllib import urlopen

url = 'http://dl.opensubtitles.org/en/download/filead/src-api/vrf-f1df5e6647/sid-59u5ljvife6rlktcl486ebmm80/1954156799.gz'


with closing(urlopen(url)) as urlfile:
    gzip_subtitle_contents = urlfile.read()

basename = url.split('/')[-1]
with open(basename, 'wb') as f:
    f.write(gzip_subtitle_contents)

with closing(gzip.GzipFile(basename, 'rb')) as f:
    subtitle_contents = f.read()

with open('sub.txt', 'w') as f:
    f.write(subtitle_contents)
```

And run it in your system? It should generate a `"sub.txt"` file in the current directory, with the correct subtitles. If it does not, please post the output you get.
