### ISSUE TITLE
Script confuses folders with files

### ISSUE THREAD

**Issue by vvojciech** [nicoddemus/ss#53]
`movies/TheMovie.avi` is in fact a directory:

```
Traceback (most recent call last):
  File "/bin/ss", line 10, in <module>
    sys.exit(main())
  File "/usr/bin/ss.py", line 381, in main
    subtitle_filename = future.result()
  File "/usr/lib/python2.7/site-packages/concurrent/futures/_base.py", line 455, in result
    return self.__get_result()
  File "/usr/lib/python2.7/site-packages/concurrent/futures/thread.py", line 63, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/bin/ss.py", line 183, in search_and_download
    subtitle_url, subtitle_ext = find_subtitle(movie_filename, language=language)
  File "/usr/bin/ss.py", line 108, in find_subtitle
    search_results = query_open_subtitles(movie_filename, language)
  File "/usr/bin/ss.py", line 90, in query_open_subtitles
    obtain_movie_hash_query(movie_filename, language),
  File "/usr/bin/ss.py", line 60, in obtain_movie_hash_query
    'moviehash': calculate_hash_for_file(movie_filename),
  File "/usr/bin/ss.py", line 233, in calculate_hash_for_file
    f = open(name, "rb")
IOError: [Errno 21] Is a directory: 'movies/TheMovie.avi'
```

**Comment by nicoddemus** [comment]
Hi @vvojciech,

That's a silly error, thanks for reporting. I would appreciate a PR fixing this btw, thanks!
